// frontend-react/src/components/Select.tsx
import { useId } from 'react'
import type { ReactNode, SelectHTMLAttributes } from 'react'

type SelectProps = SelectHTMLAttributes<HTMLSelectElement> & {
  label: string
  children: ReactNode
}

export function Select({ label, className, children, ...selectProps }: SelectProps) {
  const id = useId()

  return (
    <div className="flex flex-col gap-1.5">
      <label htmlFor={id} className="text-sm font-medium text-slate-700">
        {label}
      </label>
      <select
        id={id}
        className={[
          'w-full rounded-lg border border-slate-300 bg-white px-3.5 py-2.5 text-slate-900 shadow-sm outline-none transition',
          'focus:ring-2 focus:ring-indigo-500/40 focus:border-indigo-500',
          'disabled:cursor-not-allowed disabled:bg-slate-50 disabled:text-slate-400',
          className ?? '',
        ].join(' ')}
        {...selectProps}
      >
        {children}
      </select>
    </div>
  )
}

// frontend-vue/src/components/Select.vue
<script setup lang="ts">
import { useId } from 'vue'

defineProps<{
  modelValue: string
  label: string
  disabled?: boolean
}>()

const emit = defineEmits<{ 'update:modelValue': [value: string] }>()

const uid = useId()

function onChange(event: Event) {
  emit('update:modelValue', (event.target as HTMLSelectElement).value)
}
</script>

<template>
  <div class="flex flex-col gap-1.5">
    <label :for="uid" class="text-sm font-medium text-slate-700">{{ label }}</label>
    <select
      :id="uid"
      :value="modelValue"
      :disabled="disabled"
      class="w-full rounded-lg border border-slate-300 bg-white px-3.5 py-2.5 text-slate-900 shadow-sm outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/40 disabled:cursor-not-allowed disabled:bg-slate-50 disabled:text-slate-400"
      @change="onChange"
    >
      <slot />
    </select>
  </div>
</template>
